services:
  chat-api:
    container_name: ${REPO_NAME}-production-api
    image: ${API_IMAGE}
    restart: unless-stopped
    env_file:
      - /etc/mymemo/chat-api/env.prod
    environment:
      - NODE_ENV=production
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    mem_limit: 4g
    mem_reservation: 3g
    memswap_limit: 6g
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /apps/chat-api
        awslogs-stream: ec2-${REPO_NAME}-production-api
        awslogs-create-group: "true"

  ingest-worker:
    container_name: ${REPO_NAME}-production-worker
    image: ${WORKER_IMAGE}
    restart: unless-stopped
    env_file:
      - /etc/mymemo/chat-api/env.prod
    environment:
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    mem_limit: 2g
    mem_reservation: 1536m
    memswap_limit: 4g
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /apps/chat-api
        awslogs-stream: ec2-${REPO_NAME}-production-worker
        awslogs-create-group: "true"


