services:
  chat-api:
    container_name: chat-api
    build: .
    ports:
      - 3000:3000
    env_file:
      # -/etc/mymemo/chat-api.env
      - .env
    restart: always

  ingest-worker:
    container_name: ingest-worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      # -/etc/mymemo/chat-api.env
      - .env
    restart: always
