services:
  chat-api:
    container_name: preview-${REPO_SLUG}-${BRANCH_SLUG}-api
    image: ${API_IMAGE}
    restart: unless-stopped
    env_file:
      - /etc/mymemo/chat-api/env.dev
    environment:
      - NODE_ENV=production
    ports:
      - "${CONTAINER_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    mem_limit: 1g
    mem_reservation: 512m
    memswap_limit: 2g
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /apps/chat-api-preview
        awslogs-stream: ec2-${BRANCH_SLUG}-api
        awslogs-create-group: "true"
    networks:
      - preview-network

  rag-api:
    container_name: preview-${REPO_SLUG}-${BRANCH_SLUG}-rag-api
    image: ${RAG_API_IMAGE}
    restart: unless-stopped
    env_file:
      - /etc/mymemo/rag-python/env.dev
    ports:
      - "8000"
    mem_limit: 512m
    mem_reservation: 256m
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /apps/rag-python-preview
        awslogs-stream: ec2-${BRANCH_SLUG}-api
        awslogs-create-group: "true"
    networks:
      - preview-network

  rag-worker:
    container_name: preview-${REPO_SLUG}-${BRANCH_SLUG}-rag-worker
    image: ${RAG_WORKER_IMAGE}
    restart: unless-stopped
    env_file:
      - /etc/mymemo/rag-python/env.dev
    # TODO: Update memory limits to 512m and reservation to 256m after migration is complete
    mem_limit: 2g
    mem_reservation: 1536m
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /apps/rag-python-preview
        awslogs-stream: ec2-${BRANCH_SLUG}-worker
        awslogs-create-group: "true"
    networks:
      - preview-network

networks:
  preview-network:
    name: preview-${REPO_SLUG}-${BRANCH_SLUG}-network
    driver: bridge

