services:
  chat-api:
    container_name: chat-api
    build:
      context: ./apps/chat-api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./apps/chat-api/.env
    restart: always

  ingest-worker:
    container_name: ingest-worker
    build:
      context: ./apps/chat-api
      dockerfile: Dockerfile.worker
    env_file:
      - ./apps/chat-api/.env
    restart: always
