services:
  chat-api:
    container_name: chat-api
    build:
      context: .
      dockerfile: apps/chat-api/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./apps/chat-api/.env
    restart: always
    networks:
      - mymemo-network

networks:
  mymemo-network:
    driver: bridge
